In [ ]:

from sklearn.model_selection import train_test_split
import pandas as pd
import os
import librosa
import librosa.display
import cv2
import numpy as np
import json
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter("ignore")

In [ ]:

# Download coughvid data in CDF format
# Run once 
!git clone "https://github.com/virufy/virufy-cdf-coughvid.git"

Cloning into 'virufy-cdf-coughvid'...
remote: Enumerating objects: 22051, done.
remote: Total 22051 (delta 0), reused 0 (delta 0), pack-reused 22051
Receiving objects: 100% (22051/22051), 1006.41 MiB | 41.85 MiB/s, done.
Resolving deltas: 100% (16/16), done.
Checking out files: 100% (22045/22045), done.

In [ ]:
cough_vid = pd.read_csv("virufy-cdf-coughvid/virufy-cdf-coughvid.csv")

In [ ]:
from google.colab import drive
drive.mount('drive')

Mounted at drive

In [ ]:
file = pd.read_json("/content/drive/MyDrive/Colab Notebooks/cough/train_features.json")
test_file = pd.read_json("/content/drive/MyDrive/Colab Notebooks/cough/test_features.json")

In [ ]:
cough_vid=cough_vid.set_index("patient_id")

In [ ]:
file.columns[0]

'c6ce14bb-84c9-4176-b8ab-11c010ebe953'

In [ ]:
label = file.loc["label"].values
test_label = test_file.loc["label"].values

In [ ]:
test_label.shape

(1078,)

In [ ]:
features = file.loc["rawMFCC"].values
test_features = test_file.loc["rawMFCC"].values

In [ ]:
features

array([list([-120.25133970877937, 35.91352187844071, 0.09303300833012601, 7.580791305572749, -2.424970938894132, 3.3637031209927413, 1.040820273674449, 3.098567231920372, 1.098428159738094, 1.551151581025139, 0.6054625630193341, 0.663805352010272, 0.6265162066052421]),
       list([-131.86466087590296, 20.44464021437177, -3.657456166926314, 3.196484360949678, 0.427949681841011, 0.996431034952274, 0.073030790768533, 0.9127930095837631, -1.086254508386552, -1.890917535824391, -0.794967530862807, 0.64174740102407, 0.363290410461086]),
       list([-159.54989418557537, 29.30848503914942, -6.385037657251987, 1.654928960602555, 3.715769424251183, 1.103940788477643, 2.152272117908047, -0.535701182420757, -0.6108534415790411, -0.99469865014666, -0.48193569107717205, 0.9759793983003701, -0.928307107162166]),
       ...,
       list([-258.9950039453386, 24.250733352380255, -11.168871775620547, -0.148436317445079, 1.8001336575975682, 0.348747820150106, 1.465855865564016, -0.54972316394247, 1.041766523264024, 0.26688142711115204, -1.60824228527333, 0.14853095295541102, 0.041233273555372006]),
       list([-137.41073854119742, 36.52341210735049, -12.641692767732417, 5.825400494910214, 1.608684629984189, -3.619475385570086, 2.8715359173230013, -2.372023429643789, -0.131719541016091, -0.6596086971536971, -3.155602060140952, 1.413371470453918, -0.85350638294499]),
       list([-161.89596758045545, 27.720541872572657, -5.3043368580353665, 11.244186119062547, -3.785470303352914, -2.169302238698737, 7.943993916047369, -0.7676589239127171, 0.74220105795455, 0.286338870441926, -1.393236212635055, 1.6542071558838982, -0.938229747088218])],
      dtype=object)

In [ ]:

df = pd.DataFrame(features.tolist())
test_df = pd.DataFrame(test_features.tolist())
df["label"] = label
test_df["label"] = test_label
df.replace({"positive":1, "negative":0}, inplace=True)
test_df.replace({"positive":1, "negative":0}, inplace=True)

In [ ]:
df = df.set_index(file.columns)
test_df = test_df.set_index(test_file.columns)

In [ ]:
test_df

                                               0          1  ...        12  label
cf728002-0ccc-4717-bbb7-6ce65865d451 -158.652773  24.813539  ... -0.860287      0
b12d98ad-caa1-4630-b7d8-cf79f1e0a618 -115.985243  45.119393  ... -0.529770      0
080597cb-f0c1-4c83-87ad-441fc4bc23aa -332.506330  10.060688  ...  0.170767      0
3f609a29-fe55-400a-aa47-50a4d6b9d3bf -106.811704  48.433244  ... -1.048928      0
11caadaf-54d9-4873-b62e-5097db0dc11b -166.088953  19.677399  ... -0.501095      0
...                                          ...        ...  ...       ...    ...
cd7aeb8d-7fae-4c93-bc19-340496e94b53 -124.589779  20.228351  ...  0.285841      0
ec0be4e6-5434-482e-8685-ac35bdc553d6 -139.169075  33.834605  ... -0.394135      0
e136f725-f618-40e9-82e9-d4712a5479dd -154.615661  37.064379  ... -0.328747      1
c84aea19-25b0-4b61-a8db-9650ae12456b -252.176839  27.853138  ... -0.416205      0
eeb0acc0-0960-4047-a0ef-b18bc072ef92 -117.633529  43.213784  ... -0.175082      0

[1078 rows x 14 columns]

In [ ]:
cough_vid

                                      Unnamed: 0  ... covid_symptoms
patient_id                                        ...
ae029647-ddc3-47f5-904e-813358c9dda3           0  ...            NaN
cac4a470-bb86-4db9-9453-d4e2706c3931           1  ...            NaN
2a3d201f-7c70-449c-adc5-50de728fccd0           2  ...          False
8b267d78-97f0-4530-bbfa-e938724376f4           3  ...            NaN
68d5215b-afdb-4b7a-81d3-fbd5677de7b4           4  ...          False
...                                          ...  ...            ...
ea14155e-a4bf-4cfb-89bd-0f2c7cae0a33       22035  ...          False
76682a59-1c14-44e8-93b9-f9f5f774e897       22036  ...           True
e59eba05-4b00-41f8-924d-01110aa3cb1b       22037  ...           True
ed7e5ffe-ed3e-432f-9025-fd48fcd308df       22038  ...          False
a684a1c0-e2de-4ae2-b1a1-cca613005bd5       22039  ...           True

[22040 rows x 15 columns]

In [ ]:
clean_cough_vid = cough_vid.drop(['Unnamed: 0', 'source', 'covid_symptoms', 'cough_path', 'biological_sex', 'reported_gender', 'submission_date', 'pcr_test_date', 'pcr_result_date', 'pcr_test_result', 'pcr_test_result_inferred'], axis=1)

In [ ]:
clean_cough_vid

                                      cough_detected  ...  fever_or_muscle_pain
patient_id                                            ...
ae029647-ddc3-47f5-904e-813358c9dda3          0.8929  ...                   NaN
cac4a470-bb86-4db9-9453-d4e2706c3931          0.1431  ...                   NaN
2a3d201f-7c70-449c-adc5-50de728fccd0          0.0803  ...                 False
8b267d78-97f0-4530-bbfa-e938724376f4          0.1247  ...                   NaN
68d5215b-afdb-4b7a-81d3-fbd5677de7b4          1.0000  ...                 False
...                                              ...  ...                   ...
ea14155e-a4bf-4cfb-89bd-0f2c7cae0a33          0.3717  ...                 False
76682a59-1c14-44e8-93b9-f9f5f774e897          1.0000  ...                 False
e59eba05-4b00-41f8-924d-01110aa3cb1b          0.0380  ...                 False
ed7e5ffe-ed3e-432f-9025-fd48fcd308df          0.0068  ...                 False
a684a1c0-e2de-4ae2-b1a1-cca613005bd5          1.0000  ...                 False

[22040 rows x 4 columns]

In [ ]:
joined_df = df.join(clean_cough_vid)
joined_test_df = test_df.join(clean_cough_vid)

In [ ]:
joined_test_df

                                               0  ...  fever_or_muscle_pain
cf728002-0ccc-4717-bbb7-6ce65865d451 -158.652773  ...                 False
b12d98ad-caa1-4630-b7d8-cf79f1e0a618 -115.985243  ...                 False
080597cb-f0c1-4c83-87ad-441fc4bc23aa -332.506330  ...                 False
3f609a29-fe55-400a-aa47-50a4d6b9d3bf -106.811704  ...                   NaN
11caadaf-54d9-4873-b62e-5097db0dc11b -166.088953  ...                   NaN
...                                          ...  ...                   ...
cd7aeb8d-7fae-4c93-bc19-340496e94b53 -124.589779  ...                   NaN
ec0be4e6-5434-482e-8685-ac35bdc553d6 -139.169075  ...                   NaN
e136f725-f618-40e9-82e9-d4712a5479dd -154.615661  ...                 False
c84aea19-25b0-4b61-a8db-9650ae12456b -252.176839  ...                   NaN
eeb0acc0-0960-4047-a0ef-b18bc072ef92 -117.633529  ...                 False

[1078 rows x 18 columns]

In [ ]:
# joined_df['biological_sex'].replace({"male":1, "female":0}, inplace=True)
joined_df['respiratory_condition'].replace({True:1, False:0}, inplace=True)
joined_df['fever_or_muscle_pain'].replace({True:1, False:0}, inplace=True)
# joined_df['covid_symptoms'].replace({True:1, False:0}, inplace=True)
# joined_test_df['biological_sex'].replace({"male":1, "female":0}, inplace=True)
joined_test_df['respiratory_condition'].replace({True:1, False:0}, inplace=True)
joined_test_df['fever_or_muscle_pain'].replace({True:1, False:0}, inplace=True)
# joined_test_df['covid_symptoms'].replace({True:1, False:0}, inplace=True)

In [ ]:
joined_df

                                               0  ...  fever_or_muscle_pain
c6ce14bb-84c9-4176-b8ab-11c010ebe953 -120.251340  ...                   0.0
d630666f-3847-4daa-932b-3094a3993df0 -131.864661  ...                   1.0
f6545c93-48c3-4434-9793-90d1d19d30cd -159.549894  ...                   NaN
2e5ab77f-2365-4396-8eb5-480ebce9beb8 -164.492833  ...                   0.0
4acfc873-f11a-4c14-830d-0125bd5d23e2 -103.352107  ...                   0.0
...                                          ...  ...                   ...
4abf0305-9a19-4925-811d-4f57ef80616a -281.000222  ...                   0.0
015576c8-2b03-4dcb-b251-78a984fe86fe -160.515119  ...                   0.0
362fdba5-bb0b-424e-8265-e42a6b1715d0 -258.995004  ...                   NaN
26e4d0d9-a03c-4564-b15e-d8850bb4a2a3 -137.410739  ...                   NaN
3dc19f4e-b7b7-4100-8968-cbf155ff3fb4 -161.895968  ...                   1.0

[4308 rows x 18 columns]

In [ ]:
df = df[df["cough_detected"] >= 0.7]

KeyError: ignored

In [ ]:
joined_df.shape

(4308, 18)

In [ ]:
joined_test_df.shape

(1078, 18)

In [ ]:
joined_df.label.value_counts()

0    3915
1     393
Name: label, dtype: int64

In [ ]:
joined_test_df.label.value_counts()

0    980
1     98
Name: label, dtype: int64

In [ ]:
joined_df

                                               0  ...  fever_or_muscle_pain
c6ce14bb-84c9-4176-b8ab-11c010ebe953 -120.251340  ...                   0.0
d630666f-3847-4daa-932b-3094a3993df0 -131.864661  ...                   1.0
f6545c93-48c3-4434-9793-90d1d19d30cd -159.549894  ...                   NaN
2e5ab77f-2365-4396-8eb5-480ebce9beb8 -164.492833  ...                   0.0
4acfc873-f11a-4c14-830d-0125bd5d23e2 -103.352107  ...                   0.0
...                                          ...  ...                   ...
4abf0305-9a19-4925-811d-4f57ef80616a -281.000222  ...                   0.0
015576c8-2b03-4dcb-b251-78a984fe86fe -160.515119  ...                   0.0
362fdba5-bb0b-424e-8265-e42a6b1715d0 -258.995004  ...                   NaN
26e4d0d9-a03c-4564-b15e-d8850bb4a2a3 -137.410739  ...                   NaN
3dc19f4e-b7b7-4100-8968-cbf155ff3fb4 -161.895968  ...                   1.0

[4308 rows x 18 columns]

In [ ]:
test_df

                                               0          1  ...        12  label
cf728002-0ccc-4717-bbb7-6ce65865d451 -158.652773  24.813539  ... -0.860287      0
b12d98ad-caa1-4630-b7d8-cf79f1e0a618 -115.985243  45.119393  ... -0.529770      0
080597cb-f0c1-4c83-87ad-441fc4bc23aa -332.506330  10.060688  ...  0.170767      0
3f609a29-fe55-400a-aa47-50a4d6b9d3bf -106.811704  48.433244  ... -1.048928      0
11caadaf-54d9-4873-b62e-5097db0dc11b -166.088953  19.677399  ... -0.501095      0
...                                          ...        ...  ...       ...    ...
cd7aeb8d-7fae-4c93-bc19-340496e94b53 -124.589779  20.228351  ...  0.285841      0
ec0be4e6-5434-482e-8685-ac35bdc553d6 -139.169075  33.834605  ... -0.394135      0
e136f725-f618-40e9-82e9-d4712a5479dd -154.615661  37.064379  ... -0.328747      1
c84aea19-25b0-4b61-a8db-9650ae12456b -252.176839  27.853138  ... -0.416205      0
eeb0acc0-0960-4047-a0ef-b18bc072ef92 -117.633529  43.213784  ... -0.175082      0

[1078 rows x 14 columns]

In [ ]:
X = joined_df.drop(["label"],axis=1)
test_X = joined_test_df.drop(["label"],axis=1)
y = joined_df.label
test_y = joined_test_df.label

In [ ]:
X

                                               0  ...  fever_or_muscle_pain
c6ce14bb-84c9-4176-b8ab-11c010ebe953 -120.251340  ...                   0.0
d630666f-3847-4daa-932b-3094a3993df0 -131.864661  ...                   1.0
f6545c93-48c3-4434-9793-90d1d19d30cd -159.549894  ...                   NaN
2e5ab77f-2365-4396-8eb5-480ebce9beb8 -164.492833  ...                   0.0
4acfc873-f11a-4c14-830d-0125bd5d23e2 -103.352107  ...                   0.0
...                                          ...  ...                   ...
4abf0305-9a19-4925-811d-4f57ef80616a -281.000222  ...                   0.0
015576c8-2b03-4dcb-b251-78a984fe86fe -160.515119  ...                   0.0
362fdba5-bb0b-424e-8265-e42a6b1715d0 -258.995004  ...                   NaN
26e4d0d9-a03c-4564-b15e-d8850bb4a2a3 -137.410739  ...                   NaN
3dc19f4e-b7b7-4100-8968-cbf155ff3fb4 -161.895968  ...                   1.0

[4308 rows x 17 columns]

In [ ]:
X = df.drop(["label"],axis=1)
test_X = test_df.drop(["label"],axis=1)
y = df.label
test_y = test_df.label

In [ ]:
X

                                              0          1   ...        11        12
c6ce14bb-84c9-4176-b8ab-11c010ebe953 -120.251340  35.913522  ...  0.663805  0.626516
d630666f-3847-4daa-932b-3094a3993df0 -131.864661  20.444640  ...  0.641747  0.363290
f6545c93-48c3-4434-9793-90d1d19d30cd -159.549894  29.308485  ...  0.975979 -0.928307
2e5ab77f-2365-4396-8eb5-480ebce9beb8 -164.492833  27.401231  ... -0.205911  0.000496
4acfc873-f11a-4c14-830d-0125bd5d23e2 -103.352107  37.261400  ... -0.628170 -0.527648
...                                          ...        ...  ...       ...       ...
4abf0305-9a19-4925-811d-4f57ef80616a -281.000222   9.040180  ...  0.268468 -0.352248
015576c8-2b03-4dcb-b251-78a984fe86fe -160.515119  30.337560  ...  1.197374 -0.788763
362fdba5-bb0b-424e-8265-e42a6b1715d0 -258.995004  24.250733  ...  0.148531  0.041233
26e4d0d9-a03c-4564-b15e-d8850bb4a2a3 -137.410739  36.523412  ...  1.413371 -0.853506
3dc19f4e-b7b7-4100-8968-cbf155ff3fb4 -161.895968  27.720542  ...  1.654207 -0.938230

[4308 rows x 13 columns]

In [ ]:
import lightgbm as lgb
from sklearn.metrics import accuracy_score, f1_score, recall_score

f1s = []
recalls = []
accs = []
max_acc = 0
max_f1 = 0
max_recall = 0
for weight in range(1, 100, 1):
  clf = lgb.LGBMClassifier(class_weight={1:weight, 0: 1})
  clf.fit(X, y)
  y_predict = clf.predict(test_X)
  f1s.append(f1_score(test_y, y_predict))
  accs.append(accuracy_score(test_y, y_predict))
  recalls.append(recall_score(test_y, y_predict))
max_acc = max(accs)
pos1 = np.argmax(accs)
max_f1 = max(f1s)
pos2 = np.argmax(f1s)
max_recall = max(recalls)
pos3 = np.argmax(recalls)

In [ ]:
print('pos1', pos1)
print('pos2', pos2)
print('pos3', pos3)
print('max accuracy', max_acc)
print('max f1', max_f1)
print('max recall', max_recall)
print(f1s)

pos1 0
pos2 26
pos3 95
max accuracy 0.9090909090909091
max f1 0.5506072874493927
max recall 0.7040816326530612
[0.43023255813953487, 0.45360824742268036, 0.4723618090452262, 0.4577114427860697, 0.48803827751196177, 0.48571428571428577, 0.5023696682464455, 0.4814814814814815, 0.5178571428571429, 0.5022421524663677, 0.5087719298245614, 0.48648648648648646, 0.5299145299145299, 0.5236051502145923, 0.48275862068965514, 0.5289256198347106, 0.5210084033613446, 0.5128205128205129, 0.5333333333333333, 0.49792531120331956, 0.5126050420168068, 0.5163934426229507, 0.5338983050847458, 0.4789915966386554, 0.5062240663900415, 0.5166666666666667, 0.5506072874493927, 0.5042016806722688, 0.5, 0.5267489711934157, 0.5140562248995983, 0.5083333333333333, 0.47302904564315346, 0.5040650406504065, 0.49593495934959353, 0.5461847389558233, 0.5039370078740157, 0.5338645418326693, 0.4878048780487805, 0.5081967213114754, 0.5138339920948617, 0.4918032786885246, 0.5275590551181102, 0.5080645161290323, 0.5040650406504065, 0.5158730158730158, 0.5080645161290323, 0.5079365079365079, 0.5220883534136546, 0.5176470588235293, 0.50199203187251, 0.5099601593625498, 0.5176470588235293, 0.5214007782101168, 0.5140562248995983, 0.4830188679245283, 0.48437500000000006, 0.48437500000000006, 0.5, 0.5258964143426295, 0.5116279069767442, 0.48031496062992124, 0.5000000000000001, 0.5158730158730158, 0.5158730158730158, 0.5096525096525096, 0.5019607843137255, 0.5000000000000001, 0.4961240310077519, 0.4961832061068703, 0.5038167938931297, 0.49805447470817116, 0.48605577689243035, 0.4920634920634921, 0.5, 0.49230769230769234, 0.49606299212598426, 0.5114503816793893, 0.4981412639405204, 0.5057471264367815, 0.4961832061068703, 0.47876447876447875, 0.5076923076923077, 0.4883720930232558, 0.48412698412698413, 0.5058365758754865, 0.5095057034220533, 0.523076923076923, 0.503875968992248, 0.5153846153846154, 0.5019305019305019, 0.4902723735408561, 0.5038167938931297, 0.4822134387351778, 0.5019305019305019, 0.5328185328185328, 0.49420849420849416, 0.5095057034220533, 0.5114503816793893]

In [ ]:
recalls[3]

0.7244897959183674